### ISSUE TITLE
strap pins

### ISSUE THREAD

**Issue by seandepagnier** [ragbagger/pypilot-STM32-motor-driver#1]
https://github.com/ragbagger/pypilot-STM32-motor-driver/blob/60bb5a8efda2b8d23fd60a510614af3e29288840/Pypilot_motor/Core/Src/main.c#L348

Why not just support high current (40 amps or even more) if you arent going to do high and low boards?   It is really up to you but I would just take this out.

**Comment by ragbagger** [comment]
That was left over from Timo version too. It has been removed
