### ISSUE TITLE
rudder feedback

### ISSUE THREAD

**Issue by seandepagnier** [ragbagger/pypilot-STM32-motor-driver#2]
https://github.com/ragbagger/pypilot-STM32-motor-driver/blob/60bb5a8efda2b8d23fd60a510614af3e29288840/Pypilot_motor/Core/Src/main.c#L370

It is stored and loaded.. just that everything is implemented in python.   So pypilot will query the eeprom which is handled separately to restore rudder feedback parameters, or it may just store them on the raspberry, but either way, from these it computes the min and max rudder parameters which are then sent to the motor controller periodically.

In this way, the rudder calculation and calibration is completely decoupled from the motor controller, but the motor controller can still react to rudder being out of range which is much faster than the raspberry reacting.

**Comment by ragbagger** [comment]
This was an old todo from Timo version. It has been removed.
