### ISSUE TITLE
detach

### ISSUE THREAD

**Issue by seandepagnier** [ragbagger/pypilot-STM32-motor-driver#3]
https://github.com/ragbagger/pypilot-STM32-motor-driver/blob/60bb5a8efda2b8d23fd60a510614af3e29288840/Pypilot_motor/Core/Src/main.c#L553

Detach typically should have the same effect as if the motor is not connected electrically.   For RC style it would mean no pwm output is given which is different from a neutral signal (which may brake the motor)   So in this case all pwm outputs would be off.

**Comment by ragbagger** [comment]
It has been updated to turn off enable pins and pwm pins
